# Generated by Django 4.0.2 on 2024-08-10 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0027_product_unidadempaque'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='monedero_percentaje',
            field=models.CharField(default=0.0, max_length=100, verbose_name='monedero%'),
        ),
    ]
