# Generated by Django 4.0.2 on 2024-11-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0028_product_monedero_percentaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory_no',
            field=models.IntegerField(default=1),
        ),
    ]
