# Generated by Django 4.0.2 on 2025-01-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0029_product_inventory_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='costo',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=14),
        ),
    ]
