# Generated by Django 4.0.2 on 2025-07-29 15:58

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0031_product_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': [django.db.models.functions.text.Lower('name')], 'verbose_name': 'brand', 'verbose_name_plural': 'brands'},
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('category', 'brand', 'name'), name='unique_product_full_name'),
        ),
    ]
