# Generated by Django 4.0.2 on 2025-07-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0032_alter_brand_options_product_unique_product_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=500, verbose_name='name'),
        ),
    ]
