# Generated by Django 4.0.2 on 2025-08-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0033_alter_product_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_product_full_name',
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=500, verbose_name='barcode'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pv1',
            field=models.CharField(max_length=100),
        ),
    ]
