# Generated by Django 4.0.2 on 2025-08-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0034_remove_product_unique_product_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sat',
            field=models.BooleanField(default=False),
        ),
    ]
