# Generated by Django 4.0.2 on 2025-11-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0035_product_sat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=500, unique=True, verbose_name='barcode'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pv1',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('category', 'brand', 'name'), name='unique_product_full_name'),
        ),
    ]
