# Generated by Django 5.2.12 on 2026-05-02 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_clienttier_clienttierstatus'),
        ('im', '0036_alter_product_barcode_alter_product_pv1_and_more'),
        ('scm', '0010_repair_purchaseitem_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABCConfiguration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_period_days', models.IntegerField(choices=[(30, 'Last 30 days'), (90, 'Last 90 days'), (180, 'Last 6 months'), (365, 'Last 12 months')], default=30, verbose_name='Time Period for ABC Calculation (days)')),
                ('pareto_a_threshold', models.DecimalField(decimal_places=2, default=80.0, help_text='Percentage of revenue threshold for A classification (e.g., 80 for 80%)', max_digits=5, verbose_name='A Class Revenue Threshold (%)')),
                ('pareto_b_threshold', models.DecimalField(decimal_places=2, default=95.0, help_text='Cumulative percentage threshold for B classification (e.g., 95 for 80-95%)', max_digits=5, verbose_name='B Class Revenue Threshold (%)')),
                ('auto_recalculate', models.BooleanField(default=True, help_text='If enabled, ABC classification recalculates automatically after each transaction', verbose_name='Auto-recalculate after sales/devolutions')),
                ('last_recalculation', models.DateTimeField(blank=True, null=True, verbose_name='Last Recalculation Timestamp')),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ABC Configuration',
                'verbose_name_plural': 'ABC Configuration',
            },
        ),
        migrations.CreateModel(
            name='ProductABCMetrics',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='abc_metrics', serialize=False, to='im.product')),
                ('abc_classification', models.CharField(choices=[('A', 'A - High Value'), ('B', 'B - Medium Value'), ('C', 'C - Low Value'), ('unclassified', 'Unclassified')], db_index=True, default='unclassified', max_length=20)),
                ('last_30_days_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Revenue (Last 30 days)')),
                ('last_30_days_units_sold', models.IntegerField(default=0, verbose_name='Units Sold (Last 30 days)')),
                ('cumulative_revenue_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Cumulative Revenue %')),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Product ABC Metrics',
                'verbose_name_plural': 'Product ABC Metrics',
                'ordering': ['-abc_classification'],
            },
        ),
        migrations.CreateModel(
            name='InventoryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Tracking ID')),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('received', 'Received'), ('ready_to_sale', 'Ready to Sale'), ('sold', 'Sold'), ('retired_damaged', 'Retired - Damaged'), ('retired_other', 'Retired - Other')], db_index=True, default='ordered', max_length=20)),
                ('abc_classification', models.CharField(choices=[('A', 'A - High Value'), ('B', 'B - Medium Value'), ('C', 'C - Low Value'), ('unclassified', 'Unclassified')], db_index=True, default='unclassified', max_length=20)),
                ('ordered_date', models.DateTimeField(blank=True, null=True)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('ready_date', models.DateTimeField(blank=True, null=True)),
                ('sold_date', models.DateTimeField(blank=True, null=True)),
                ('retired_date', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_units', to='im.product')),
                ('purchase_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_units', to='scm.purchaseitem')),
                ('sale_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_units', to='crm.saleitem')),
            ],
            options={
                'verbose_name': 'Inventory Unit',
                'verbose_name_plural': 'Inventory Units',
                'ordering': ['-tracking_id'],
                'indexes': [models.Index(fields=['tracking_id'], name='im_inventor_trackin_52738a_idx'), models.Index(fields=['status'], name='im_inventor_status_474dd1_idx'), models.Index(fields=['abc_classification'], name='im_inventor_abc_cla_395d83_idx'), models.Index(fields=['product', 'status'], name='im_inventor_product_13753f_idx'), models.Index(fields=['-date_created'], name='im_inventor_date_cr_bff7b9_idx')],
            },
        ),
    ]
