# Generated by Django 5.2.12 on 2026-05-02 19:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0037_abcconfiguration_productabcmetrics_inventoryunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryunit',
            name='purchase_cost',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), help_text='Cost per unit at time of purchase', max_digits=14, verbose_name='Purchase Cost'),
        ),
    ]
