# Generated by Django 5.2.12 on 2026-05-02 19:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0038_inventoryunit_purchase_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='demand_forecast', serialize=False, to='im.product')),
                ('forecast_daily', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Daily Forecast')),
                ('forecast_30days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='30-Day Forecast')),
                ('confidence_level', models.IntegerField(default=0, verbose_name='Confidence Level (%)')),
                ('lower_bound', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Lower Bound (95% CI)')),
                ('upper_bound', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Upper Bound (95% CI)')),
                ('trend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Trend Component')),
                ('mape', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=5, verbose_name='Mean Absolute % Error')),
                ('reorder_point', models.IntegerField(default=0, verbose_name='Recommended Reorder Point')),
                ('eoq', models.IntegerField(default=0, verbose_name='Economic Order Quantity')),
                ('last_sales_data_count', models.IntegerField(default=0, verbose_name='Data Points Used')),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Demand Forecast',
                'verbose_name_plural': 'Demand Forecasts',
                'ordering': ['-forecast_daily'],
            },
        ),
        migrations.CreateModel(
            name='ForecastConfiguration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alpha', models.DecimalField(decimal_places=2, default=Decimal('0.30'), help_text='0.1-0.5: Higher = more responsive to recent changes', max_digits=3, verbose_name='Alpha (Smoothing Coefficient)')),
                ('beta', models.DecimalField(decimal_places=2, default=Decimal('0.10'), help_text='0.01-0.2: Higher = stronger trend influence', max_digits=3, verbose_name='Beta (Trend Coefficient)')),
                ('lookback_period_days', models.IntegerField(default=90, help_text='Number of historical days to use for forecasting', verbose_name='Lookback Period (days)')),
                ('forecast_horizon_days', models.IntegerField(default=30, help_text='Number of days ahead to forecast', verbose_name='Forecast Horizon (days)')),
                ('include_seasonality', models.BooleanField(default=True, verbose_name='Include Seasonality Adjustment')),
                ('safety_stock_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='1.5 = 50% safety buffer', max_digits=3, verbose_name='Safety Stock Multiplier')),
                ('supplier_lead_time_days', models.IntegerField(default=7, verbose_name='Supplier Lead Time (days)')),
                ('auto_recalculate', models.BooleanField(default=True, help_text='Recalculate when new sales are recorded', verbose_name='Auto-recalculate forecasts')),
                ('last_recalculation', models.DateTimeField(blank=True, null=True, verbose_name='Last Recalculation')),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Forecast Configuration',
                'verbose_name_plural': 'Forecast Configuration',
            },
        ),
    ]
