# Generated by Django 5.2.12 on 2026-05-02 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0039_demandforecast_forecastconfiguration'),
        ('scm', '0011_purchaseorder_purchaseorderitem_orderlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryunit',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_units', to='scm.purchaseorder'),
        ),
    ]
