# Generated by Django 5.2.12 on 2026-05-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0040_inventoryunit_purchase_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryunit',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('send', 'Send'), ('received', 'Received'), ('ready_to_sale', 'Ready to Sale'), ('sold', 'Sold'), ('retired_damaged', 'Retired - Damaged'), ('retired_other', 'Retired - Other')], db_index=True, default='ordered', max_length=20),
        ),
    ]
