# Generated by Django 5.2.12 on 2026-05-02 23:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0041_alter_inventoryunit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryunit',
            name='received_cost',
            field=models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.00'), help_text='Actual cost per unit when received (may differ from purchase cost)', max_digits=14, null=True, verbose_name='Received Cost'),
        ),
    ]
