# Generated by Django 5.2.12 on 2026-05-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0042_inventoryunit_received_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='precio_granel_manual',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=14, null=True, verbose_name='Precio Granel Manual'),
        ),
        migrations.AddField(
            model_name='product',
            name='precio_manual',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=14, null=True, verbose_name='Precio Manual'),
        ),
        migrations.AddField(
            model_name='product',
            name='precio_mayoreo_manual',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=14, null=True, verbose_name='Precio Mayoreo Manual'),
        ),
    ]
