# Generated by Django 5.2.12 on 2026-05-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0043_product_precio_granel_manual_product_precio_manual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='granel_pricing_mode',
            field=models.CharField(choices=[('margin', 'Usar Margen'), ('price', 'Usar Precio Manual')], default='margin', max_length=10, verbose_name='Modo Precio Granel'),
        ),
        migrations.AddField(
            model_name='product',
            name='mayoreo_pricing_mode',
            field=models.CharField(choices=[('margin', 'Usar Margen'), ('price', 'Usar Precio Manual')], default='margin', max_length=10, verbose_name='Modo Precio Mayoreo'),
        ),
        migrations.AddField(
            model_name='product',
            name='pricing_mode',
            field=models.CharField(choices=[('margin', 'Usar Margen'), ('price', 'Usar Precio Manual')], default='margin', max_length=10, verbose_name='Modo Precio Regular'),
        ),
    ]
