# Generated by Django 5.2.12 on 2026-05-05 19:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0044_product_granel_pricing_mode_and_more'),
        ('scm', '0012_alter_purchaseorderitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pv1', models.CharField(help_text="This provider's internal SKU/code for this product", max_length=100, verbose_name='Provider PV1')),
                ('provider_cost', models.DecimalField(decimal_places=6, default=Decimal('0.00'), help_text='Cost per unit from this specific provider', max_digits=14, verbose_name='Provider Cost')),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_pairs', to='im.product', verbose_name='Product')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_pairs', to='scm.provider', verbose_name='Provider')),
            ],
            options={
                'verbose_name': 'Product Provider',
                'verbose_name_plural': 'Product Providers',
                'ordering': ['product', 'provider'],
                'unique_together': {('product', 'provider')},
            },
        ),
    ]
