# Generated by Django 5.2.12 on 2026-05-05 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0045_productprovider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pv1',
        ),
    ]
