# Generated by Django 5.2.12 on 2026-05-05 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0046_remove_product_pv1'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAudit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('audit_date', models.DateField(auto_now_add=True, verbose_name='Audit Date')),
                ('audit_type', models.CharField(choices=[('random', 'Random Sample (20 items)'), ('random_custom', 'Random Sample (Custom Count)'), ('full', 'Full Inventory'), ('category', 'By Category'), ('manual', 'Manual Selection')], max_length=20, verbose_name='Audit Type')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('under_review', 'Under Review'), ('completed', 'Completed')], default='draft', max_length=20, verbose_name='Status')),
                ('auditor', models.CharField(max_length=150, verbose_name='Auditor')),
                ('reviewed_by', models.CharField(blank=True, max_length=150, null=True, verbose_name='Reviewed By')),
                ('total_items_audited', models.IntegerField(default=0, verbose_name='Total Items Audited')),
                ('total_discrepancies', models.IntegerField(default=0, verbose_name='Total Discrepancies')),
                ('total_adjustment_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Adjustment Value')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Inventory Audit',
                'verbose_name_plural': 'Inventory Audits',
                'ordering': ['-audit_date'],
            },
        ),
        migrations.CreateModel(
            name='AuditItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('system_count', models.IntegerField(verbose_name='System Count')),
                ('physical_count', models.IntegerField(verbose_name='Physical Count')),
                ('discrepancy', models.IntegerField(verbose_name='Discrepancy')),
                ('adjustment_reason', models.CharField(blank=True, choices=[('stolen', 'Stolen'), ('damaged', 'Damaged/Unusable'), ('warranty', 'Warranty Return'), ('miscounted', 'System Miscounted'), ('expired', 'Expired/Obsolete'), ('shrinkage', 'Unknown Shrinkage'), ('correction', 'Manual Correction'), ('other', 'Other')], max_length=20, null=True, verbose_name='Adjustment Reason')),
                ('adjustment_status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('applied', 'Applied'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Adjustment Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('verified_by', models.CharField(blank=True, max_length=150, null=True, verbose_name='Verified By')),
                ('approved_by', models.CharField(blank=True, max_length=150, null=True, verbose_name='Approved By')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='im.product', verbose_name='Product')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='im.inventoryaudit', verbose_name='Audit')),
            ],
            options={
                'verbose_name': 'Audit Item',
                'verbose_name_plural': 'Audit Items',
                'ordering': ['product__name'],
                'unique_together': {('audit', 'product')},
            },
        ),
        migrations.CreateModel(
            name='AdjustmentTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adjustment_reason', models.CharField(max_length=20, verbose_name='Reason')),
                ('quantity_adjusted', models.IntegerField(verbose_name='Quantity Adjusted')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('unit_cost', models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Unit Cost')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Adjustment Value')),
                ('recorded_by', models.CharField(max_length=150, verbose_name='Recorded By')),
                ('applied_by', models.CharField(blank=True, max_length=150, null=True, verbose_name='Applied By')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='Applied At')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='im.product', verbose_name='Product')),
                ('audit_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment', to='im.audititem', verbose_name='Audit Item')),
            ],
            options={
                'verbose_name': 'Adjustment Transaction',
                'verbose_name_plural': 'Adjustment Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
