# Generated by Django 5.2.12 on 2026-05-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0047_inventoryaudit_audititem_adjustmenttransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryunit',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('send', 'Send'), ('received', 'Received'), ('ready_to_sale', 'Ready to Sale'), ('sold', 'Sold'), ('retired_stolen', 'Retired - Stolen'), ('retired_damaged', 'Retired - Damaged'), ('retired_warranty', 'Retired - Warranty Return'), ('retired_miscounted', 'Retired - System Miscounted'), ('retired_expired', 'Retired - Expired/Obsolete'), ('retired_shrinkage', 'Retired - Unknown Shrinkage'), ('retired_correction', 'Retired - Manual Correction'), ('retired_other', 'Retired - Other')], db_index=True, default='ordered', max_length=20),
        ),
    ]
