# Generated by Django 5.2.12 on 2026-05-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0052_populate_product_clave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='clave',
            field=models.CharField(blank=True, help_text='Unique identifier for the product. Defaults to the product ID.', max_length=100, null=True, verbose_name='Clave'),
        ),
    ]
