# Generated by Django 5.2.12 on 2026-05-12 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0053_remove_clave_unique_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
