# Generated by Django 5.2.12 on 2026-05-14 23:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0054_remove_product_stock_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprovider',
            name='unidad_empaque',
            field=models.CharField(default='1', help_text='Pieces per bundle (1 = individual piece)', max_length=100, verbose_name='Unidad Empaque'),
        ),
        migrations.AlterField(
            model_name='productprovider',
            name='provider_cost',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), help_text='Cost per bundle/package from this provider', max_digits=14, verbose_name='Provider Cost (Bundle)'),
        ),
    ]
