# Generated by Django 5.2.12 on 2026-05-14 23:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0055_productprovider_unidad_empaque_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productprovider',
            old_name='provider_cost',
            new_name='bundle_price',
        ),
    ]
