# Generated by Django 5.2.12 on 2026-05-16 18:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0056_rename_provider_cost_productprovider_bundle_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='inventory_no',
        ),
        migrations.RemoveField(
            model_name='product',
            name='monedero_percentaje',
        ),
        migrations.RemoveField(
            model_name='product',
            name='provedor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unidadEmpaque',
        ),
        migrations.AlterField(
            model_name='productprovider',
            name='bundle_price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), help_text='Price for the entire bundle/package from this provider', max_digits=14, verbose_name='Bundle Price'),
        ),
    ]
