# Generated by Django 5.2.12 on 2026-05-16 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0057_remove_product_inventory_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Group Name')),
                ('stockMin', models.PositiveIntegerField(default=0, verbose_name='Min Stock (Group)')),
                ('stockMax', models.PositiveIntegerField(default=0, verbose_name='Max Stock (Group)')),
                ('active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Product Group',
                'verbose_name_plural': 'Product Groups',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='im.productgroup', verbose_name='Grupo equivalente'),
        ),
    ]
