# Generated by Django 5.2.12 on 2026-05-21 19:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0059_product_granel_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='granel_stock',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Stock Granel (Convertido)'),
        ),
        migrations.CreateModel(
            name='GranelConversionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_per_source', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Cuantas unidades del producto destino genera una unidad del origen (ej: 100 = 1 rollo → 100 metros)', max_digits=14, verbose_name='Unidades por Origen')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('destination_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granel_conversion_as_dest', to='im.product', verbose_name='Producto Destino')),
                ('source_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='granel_conversion_as_source', to='im.product', verbose_name='Producto Origen')),
            ],
            options={
                'verbose_name': 'Configuración de Conversión Granel',
                'verbose_name_plural': 'Configuraciones de Conversión Granel',
            },
        ),
        migrations.CreateModel(
            name='GranelConversionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_quantity', models.DecimalField(decimal_places=2, help_text='Cuantas unidades del producto origen se convirtieron', max_digits=14, verbose_name='Cantidad Origen')),
                ('destination_quantity', models.DecimalField(decimal_places=2, help_text='Cuantas unidades del producto destino se generaron', max_digits=14, verbose_name='Cantidad Destino')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_logs', to='im.granelconversionconfig', verbose_name='Configuración')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Conversión Granel',
                'verbose_name_plural': 'Registros de Conversión Granel',
                'ordering': ['-date_created'],
            },
        ),
    ]
