# Generated by Django 5.2.12 on 2026-05-21 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0060_product_granel_stock_granelconversionconfig_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='granelconversionconfig',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='inventoryunit',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('send', 'Send'), ('received', 'Received'), ('ready_to_sale', 'Ready to Sale'), ('sold', 'Sold'), ('retired_stolen', 'Retired - Stolen'), ('retired_damaged', 'Retired - Damaged'), ('retired_warranty', 'Retired - Warranty Return'), ('retired_miscounted', 'Retired - System Miscounted'), ('retired_expired', 'Retired - Expired/Obsolete'), ('retired_shrinkage', 'Retired - Unknown Shrinkage'), ('retired_correction', 'Retired - Manual Correction'), ('retired_converted', 'Retired - Converted to Granel'), ('retired_other', 'Retired - Other')], db_index=True, default='ordered', max_length=20),
        ),
    ]
