# Generated by Django 5.2.12 on 2026-05-21 21:28

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0061_granelconversionconfig_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GranelConversionConfig',
            new_name='DespieceConfig',
        ),
        migrations.RenameModel(
            old_name='GranelConversionLog',
            new_name='DespieceLog',
        ),
        migrations.AlterModelOptions(
            name='despiececonfig',
            options={'verbose_name': 'Configuración de Despiece', 'verbose_name_plural': 'Configuraciones de Despiece'},
        ),
        migrations.AlterModelOptions(
            name='despiecelog',
            options={'ordering': ['-date_created'], 'verbose_name': 'Registro de Despiece', 'verbose_name_plural': 'Registros de Despiece'},
        ),
        migrations.AlterField(
            model_name='product',
            name='granel_stock',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Stock Despiece'),
        ),
    ]
