# Generated by Django 5.2.12 on 2026-05-21 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0062_rename_granelconversionconfig_despiececonfig_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='granel_stock',
        ),
    ]
