# Generated by Django 5.2.12 on 2026-05-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0064_alter_inventoryunit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryaudit',
            name='audit_type',
            field=models.CharField(choices=[('random', 'Random Sample (20 items)'), ('random_custom', 'Random Sample (Custom Count)'), ('full', 'Full Inventory'), ('category', 'By Category'), ('manual', 'Manual Selection'), ('bulk', 'Bulk Audit')], max_length=20, verbose_name='Audit Type'),
        ),
    ]
