# Generated by Django 5.2.12 on 2026-05-25 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0065_alter_inventoryaudit_audit_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_type', models.CharField(choices=[('low_margin', 'Low Margin')], max_length=20, unique=True, verbose_name='Tipo')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('threshold', models.DecimalField(decimal_places=2, help_text='Porcentaje mínimo antes de disparar alarma', max_digits=10, verbose_name='Umbral (%)')),
                ('enabled', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Configuración de Alarma',
                'verbose_name_plural': 'Configuraciones de Alarma',
            },
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor Actual')),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Umbral')),
                ('status', models.CharField(choices=[('active', 'Active'), ('dismissed', 'Dismissed'), ('resolved', 'Resolved')], default='active', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resuelto')),
                ('resolved_by', models.CharField(blank=True, max_length=150, null=True, verbose_name='Resuelto por')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='im.product', verbose_name='Producto')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='im.alarmconfig', verbose_name='Configuración')),
            ],
            options={
                'verbose_name': 'Alarma',
                'verbose_name_plural': 'Alarmas',
                'ordering': ['-created_at'],
            },
        ),
    ]
