# Generated by Django 5.2.12 on 2026-05-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0066_alarmconfig_alarm'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmconfig',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Comprobación'),
        ),
    ]
