# Generated by Django 5.2.12 on 2026-05-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0067_alarmconfig_last_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('skipped', 'Skipped'), ('resolved', 'Resolved')], default='active', max_length=20, verbose_name='Estado'),
        ),
    ]
