# Generated by Django 5.2.12 on 2026-05-28 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0068_alter_alarm_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='im.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='alarmconfig',
            name='alarm_type',
            field=models.CharField(choices=[('low_margin', 'Low Margin'), ('missing_random_audit', 'Missing Random Audit')], max_length=20, unique=True, verbose_name='Tipo'),
        ),
    ]
