# Generated by Django 5.2.12 on 2026-05-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0069_alter_alarm_product_alter_alarmconfig_alarm_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='on_promotion',
            field=models.BooleanField(default=False, verbose_name='En Promoción/Oferta'),
        ),
    ]
