# Generated by Django 5.2.12 on 2026-06-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0071_product_tiene_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryunit',
            name='purchase_with_iva',
            field=models.BooleanField(default=False, help_text='Esta unidad fue comprada con factura que incluye IVA', verbose_name='Comprado con IVA'),
        ),
    ]
