# Generated by Django 5.2.12 on 2026-06-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0073_backfill_purchase_with_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryaudit',
            name='audit_type',
            field=models.CharField(choices=[('random', 'Random Sample (20 items)'), ('random_custom', 'Random Sample (Custom Count)'), ('full', 'Full Inventory'), ('category', 'By Category'), ('manual', 'Manual Selection'), ('bulk', 'Bulk Audit'), ('physical', 'Physical Inventory (Scan)')], max_length=20, verbose_name='Audit Type'),
        ),
    ]
