# Generated by Django 5.2.12 on 2026-06-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0074_alter_inventoryaudit_audit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryaudit',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
    ]
