# Generated by Django 5.2.12 on 2026-06-10 22:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0075_inventoryaudit_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audititem',
            name='counted_by',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Counted By'),
        ),
        migrations.AddField(
            model_name='inventoryaudit',
            name='collaborators',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Collaborators'),
        ),
    ]
