# Generated by Django 5.2.12 on 2026-06-15 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0076_audititem_counted_by_inventoryaudit_collaborators'),
        ('scm', '0016_alter_purchaseorderitem_received_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryaudit',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scm.provider', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='inventoryaudit',
            name='audit_type',
            field=models.CharField(choices=[('random', 'Random Sample (20 items)'), ('random_custom', 'Random Sample (Custom Count)'), ('full', 'Full Inventory'), ('category', 'By Category'), ('manual', 'Manual Selection'), ('bulk', 'Bulk Audit'), ('physical', 'Physical Inventory (Scan)'), ('provider', 'Por Proveedor (Escáner)')], max_length=20, verbose_name='Audit Type'),
        ),
    ]
