# Generated by Django 5.2.12 on 2026-06-24 16:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0077_inventoryaudit_provider_type_and_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandforecast',
            name='mape',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=8, verbose_name='Mean Absolute % Error'),
        ),
    ]
