# Generated by Django 5.2.12 on 2026-09-07 22:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0078_alter_demandforecast_mape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprovider',
            name='unidad_empaque',
            field=models.CharField(default='1', help_text='Pieces per bundle (1 = individual piece). Enteros solamente.', max_length=100, validators=[django.core.validators.RegexValidator('^[1-9]\\d*$', 'Solo se permiten números enteros positivos mayores a cero (sin decimales, sin negativos).')], verbose_name='Unidad Empaque'),
        ),
    ]
