# Generated by Django 5.2.12 on 2026-09-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0079_alter_productprovider_unidad_empaque'),
    ]

    operations = [
        migrations.AddField(
            model_name='despiecelog',
            name='destination_unit_ids',
            field=models.JSONField(blank=True, default=list, help_text='Tracking IDs de las unidades del destino creadas en esta conversión', verbose_name='Unidades destino creadas'),
        ),
        migrations.AddField(
            model_name='despiecelog',
            name='reverted',
            field=models.BooleanField(default=False, verbose_name='Revertido'),
        ),
        migrations.AddField(
            model_name='despiecelog',
            name='source_unit_ids',
            field=models.JSONField(blank=True, default=list, help_text='Tracking IDs de las unidades del origen retiradas en esta conversión', verbose_name='Unidades origen retiradas'),
        ),
    ]
