# Generated by Django 4.0.2 on 2025-01-13 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0007_alter_purchaseitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-id'], 'verbose_name': 'purchase', 'verbose_name_plural': 'purchases'},
        ),
    ]
