# Generated by Django 4.0.2 on 2025-07-29 15:58

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0008_alter_purchase_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': [django.db.models.functions.text.Lower('name')], 'verbose_name': 'Provider', 'verbose_name_plural': 'Providers'},
        ),
    ]
