# Generated by Django 5.2.12 on 2026-05-04 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0042_inventoryunit_received_cost'),
        ('scm', '0011_purchaseorder_purchaseorderitem_orderlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='im.product', verbose_name='Product'),
        ),
    ]
