# Generated by Django 5.2.12 on 2026-05-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0012_alter_purchaseorderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='order_type',
            field=models.CharField(choices=[('instant', 'Instant Purchase'), ('auto_forecast', 'Auto from Forecast'), ('manual_stock', 'Manual from Min/Max')], default='manual_stock', max_length=20, verbose_name='Order Type'),
        ),
    ]
