# Generated by Django 5.2.12 on 2026-05-21 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0013_add_order_type_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorderitem',
            options={'ordering': ['product_id'], 'verbose_name': 'Purchase Order Item', 'verbose_name_plural': 'Purchase Order Items'},
        ),
    ]
