# Generated by Django 5.2.12 on 2026-06-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0014_alter_purchaseorderitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='has_iva',
            field=models.BooleanField(default=False, verbose_name='Factura con IVA'),
        ),
    ]
