# Generated by Django 5.2.12 on 2026-06-02 21:45

from django.db import migrations, models


def set_zero_received_qty_to_none(apps, schema_editor):
    """Convert received_quantity=0 to None (0 was the default but never explicitly set)"""
    PurchaseOrderItem = apps.get_model('scm', 'PurchaseOrderItem')
    PurchaseOrderItem.objects.filter(received_quantity=0).update(received_quantity=None)


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0015_purchaseorder_has_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='received_quantity',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Received Quantity'),
        ),
        migrations.RunPython(
            set_zero_received_qty_to_none,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
