# Generated by Django 5.2.12 on 2026-10-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('ticket', 'Ticket'), ('label', 'Label')], default='ticket', max_length=10)),
                ('ticket_type', models.CharField(blank=True, default='', max_length=20)),
                ('ref_id', models.IntegerField(blank=True, null=True)),
                ('value', models.CharField(blank=True, default='', max_length=255)),
                ('copies', models.PositiveIntegerField(default=1)),
                ('blank', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
