# Generated by Django 4.0.2 on 2025-01-13 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0030_alter_product_costo'),
        ('crm', '0023_devolution_monedero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('tipo', models.CharField(choices=[('menudeo', 'menudeo'), ('mayoreo', 'mayoreo')], default='menudeo', max_length=100)),
                ('monedero', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(default='mostrador', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.client')),
            ],
            options={
                'verbose_name': 'quote',
                'verbose_name_plural': 'quotes',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-id'], 'verbose_name': 'sale', 'verbose_name_plural': 'sales'},
        ),
        migrations.CreateModel(
            name='quoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(default=0, max_length=50)),
                ('cost', models.CharField(blank=True, max_length=50, null=True)),
                ('margen', models.CharField(default=0, max_length=100, verbose_name='margen')),
                ('monedero', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='im.product')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.quote')),
            ],
            options={
                'verbose_name': 'quoteItem',
                'verbose_name_plural': 'quotesItems',
                'ordering': ['-id'],
            },
        ),
    ]
