# Generated by Django 4.0.2 on 2025-08-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_quote_alter_sale_options_quoteitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sat',
            field=models.BooleanField(default=False),
        ),
    ]
