# Generated by Django 5.2.12 on 2026-04-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_saleitem_price_saleitem_sat'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolution',
            name='tipo',
            field=models.CharField(choices=[('menudeo', 'menudeo'), ('mayoreo', 'mayoreo')], default='menudeo', max_length=100),
        ),
    ]
