# Generated by Django 5.2.12 on 2026-04-29 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_devolution_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze')], max_length=50, unique=True, verbose_name='Tier Name')),
                ('min_monthly_sales', models.DecimalField(decimal_places=2, help_text='Minimum sales amount required to maintain this tier', max_digits=12, verbose_name='Minimum Monthly Sales Amount')),
                ('wallet_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of sale amount added to client wallet', max_digits=5, verbose_name='Wallet Reward Percentage')),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Client Tier',
                'verbose_name_plural': 'Client Tiers',
                'ordering': ['-min_monthly_sales'],
            },
        ),
        migrations.CreateModel(
            name='ClientTierStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_30_days_sales', models.DecimalField(decimal_places=2, default=0, help_text='Total sales from the last 30 days', max_digits=12, verbose_name='Last 30 Days Sales')),
                ('last_calculated', models.DateTimeField(blank=True, null=True, verbose_name='Last Tier Calculated')),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tier_status', to='crm.client', verbose_name='Client')),
                ('tier', models.ForeignKey(blank=True, help_text='Automatically calculated based on last 30 days average sales', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.clienttier', verbose_name='Current Tier')),
            ],
            options={
                'verbose_name': 'Client Tier Status',
                'verbose_name_plural': 'Client Tier Statuses',
                'ordering': ['client'],
            },
        ),
    ]
