# Generated by Django 5.2.12 on 2026-06-13 19:06

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_sale_payment_method_sale_status_sale_total_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff_time', models.TimeField(default=datetime.time(17, 30), verbose_name='Cutoff Time')),
            ],
            options={
                'verbose_name': 'Caja Configuration',
                'verbose_name_plural': 'Caja Configuration',
            },
        ),
        migrations.CreateModel(
            name='CashRegisterSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cash Register Session',
                'verbose_name_plural': 'Cash Register Sessions',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='CashCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_1000', models.IntegerField(default=0)),
                ('bill_500', models.IntegerField(default=0)),
                ('bill_200', models.IntegerField(default=0)),
                ('bill_100', models.IntegerField(default=0)),
                ('bill_50', models.IntegerField(default=0)),
                ('bill_20', models.IntegerField(default=0)),
                ('coin_10', models.IntegerField(default=0)),
                ('coin_5', models.IntegerField(default=0)),
                ('coin_2', models.IntegerField(default=0)),
                ('coin_1', models.IntegerField(default=0)),
                ('coin_50ctv', models.IntegerField(default=0)),
                ('counted_card_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('counted_check_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('counted_cash_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_counted', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_cash_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_card_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_check_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_difference', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_difference', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash_count', to='crm.cashregistersession')),
            ],
            options={
                'verbose_name': 'Cash Count (Arqueo)',
                'verbose_name_plural': 'Cash Counts (Arqueos)',
            },
        ),
    ]
