# Generated by Django 5.2.12 on 2026-06-13 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_cajaconfig_cashregistersession_cashcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolutionitem',
            name='purchase_with_iva',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devolutionitem',
            name='sale_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.saleitem'),
        ),
    ]
