# Generated by Django 5.2.12 on 2026-06-13 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_devolutionitem_sale_item_purchase_with_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajaconfig',
            name='cutoff_time_saturday',
            field=models.TimeField(default=datetime.time(15, 0), verbose_name='Cutoff Sábado'),
        ),
        migrations.AlterField(
            model_name='cajaconfig',
            name='cutoff_time',
            field=models.TimeField(default=datetime.time(17, 30), verbose_name='Cutoff Lunes-Viernes'),
        ),
    ]
