# Generated by Django 5.2.12 on 2026-07-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_cajaconfig_per_day_cutoff_and_carryover'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregistersession',
            name='post_cutoff_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Efectivo post-corte (va al siguiente día)'),
        ),
    ]
